@startuml
skinparam linestyle ortho
agent "Professor" as professor
agent "E-mail Service" as emailService
agent "Account" as account
circle "Start" as start

start -up-> professor: 1: sendCoins(coins: int, studentId: String)
professor -right-> account: 1.1: findAccount(professorId: String)
professor -up-> account: 1.2: findAccount(advantageId: String)
professor -left-> emailService: 1.3: sendEmail(advantage: Advantage, cupom: String)
@enduml