@startuml

node "Front-end" as FrontEnd

node "Back-end" as BackEnd {
    component User
    component Autentication
    component Finance
    component Benefit
    component Notification
}

node "Banco de Dados" as DB {
    component Persistence
}

interface Autenticate
interface Persist
interface "Send Email" as SendEmail
interface "Manage Benefit" as MangeBen
interface "Redeem Benefit" as RedeemBen
interface "Consult Transactions" as ConsultTrans
interface "Consult Balance" as ConsultBal
interface "Transfer Coins" as TransferCoins

Autenticate -right- Autentication
SendEmail -down- Notification
MangeBen - Benefit
RedeemBen - Benefit
Persist -down- Persistence
Finance - ConsultTrans
ConsultBal -up- Finance
TransferCoins - Finance

User --up-( Autenticate
User --down-( Persist
User --up-( ConsultTrans
User --up-( ConsultBal
User --up-( TransferCoins
User --up-( MangeBen
User --up-( RedeemBen

Benefit --down-( SendEmail
Benefit --down-( Persist
Benefit --up-( ConsultBal

Finance --down-( SendEmail
Finance --down-( Persist

FrontEnd --right- BackEnd : <<HTTP>>
BackEnd --right- DB : <<ODBC>>

@enduml