@startuml

actor "Cliente" as cliente
participant ":Advantage" as ad
participant ":AdvantageRouter" as adRouter
participant ":AdvantageController" as adController
participant ":AdvantageRepository" as adRepository
participant ":AdvantageService" as adService

ref over cliente, ad: login successful

cliente -> ad : listAdvantages()
ad -> adRouter : GET: /list
adRouter -> adController : listAllAdvantages()
adController -> adRepository : listAllAdvantages()
adRepository -> adService : listAllAdvantages()
alt advantages getted successfully
    ad --> cliente : advantages: Advantages[]
else
    ad --> cliente : Error getting advantages
end
@enduml