@startuml

class User {
    -id: Long
    -name: String
    -email: String
    -password: String
    -vehicles: List<Vehicle>
    +login(String password): boolean
    +void makeVehicleAvailable(Vehicle vehicle)
}

class Client {
    -id: Long
    -RG: String
    -CPF: String
    -address: String
    -profession: String
    -employer: String
    -lastThreeSalaries: double[]
    +void requestRent(Vehicle vehicle)
    +void modifyRentRequest(Vehicle vehicle)
    +void cancelRentRequest(Vehicle vehicle)
    +void searchRequest(Vehicle vehicle)
}


class Agent {
    +Contract modifyRentalRequest(Contract contract)
    +void analyzeRequest(Contract contract)
    +void issueOpinion(Contract contract, ContractStatus status)
    +void makeContractAvailable(Contract contract)
    +void addConsideration(Contract contract, String consideration)
}

class Bank {
    +boolean acceptCreditContract(Contract contract)
}

class Contract {
    -id: int
    -client: Client
    -owner: User
    -status: ContractStatus
    -considerations: String
    -vehicle: Vehicle
    -value: double
    -startDate: Date
    -endDate: Date
}
 
class CreditContract {
    -id: int
    -credit: double
}

class Vehicle {
    -id: int
    -registration: String
    -year: int
    -brand: String
    -model: String
    -plate: String
    -status: VehicleStatus
}

enum ContractStatus {
    PENDING
    APPROVED
    REJECTED
}

enum VehicleStatus {
    AVAILABLE
    RENTED
}

User <|-- Agent
User <|-- Client
User "1" -- "0..*" Vehicle
Contract <|-- CreditContract
Client "1" -- "0..*" Contract
CreditContract "1" -- "1" Bank
Contract "1" -- "1" Vehicle
Agent <|-- Bank
Agent "1" -- "0..*" Contract
@enduml