@startuml

package Model {
    class User
    class Client
    class Agent
    class Bank
    class Vehicle
    class Contract
    class CreditContract
}

package Controller {
    class UserController
    class ClientController
    class AgentController
    class BankController
    class VehicleController
    class ContractController
    class CreditContractController
}

package View {
    class UserView
    class ClientView
    class AgentView
    class BankView
    class VehicleView
    class ContractView
    class CreditContractView
}

package Interface {
    class Swagger
}

package Enums {
    enum VehicleStatus
    enum ContractStatus
}

User <.. UserController
UserController <.. UserView
UserView <.. Swagger

Client <.. ClientController
ClientController <.. ClientView
ClientView <.. Swagger

Agent <.. AgentController
AgentController <.. AgentView
AgentView <.. Swagger

Bank <.. BankController
BankController <.. BankView
BankView <.. Swagger

Vehicle <.. VehicleController
VehicleController <.. VehicleView
VehicleView <.. Swagger

Contract <.. ContractController
ContractController <.. ContractView
ContractView <.. Swagger

CreditContract <.. CreditContractController
CreditContractController <.. CreditContractView
CreditContractView <.. Swagger

@enduml