@startuml

package Model {
    class UserModel
    class ClientModel
    class AgentModel
    class BankModel
    class VehicleModel
    class ContractModel
    class CreditContractModel
}

package Controller {
    class UserController
    class ClientController
    class AgentController
    class BankController
    class VehicleController
    class ContractController
    class CreditContractController
}

package View {
    class UserView
    class ClientView
    class AgentView
    class BankView
    class VehicleView
    class ContractView
    class CreditContractView
}

package Interface {
    class Swagger
}

package Enums {
    enum VehicleStatus
    enum ContractStatus
}

UserModel -- UserController
UserController -- UserView
UserView -- Swagger

ClientModel -- ClientController
ClientController -- ClientView
ClientView -- Swagger

AgentModel -- AgentController
AgentController -- AgentView
AgentView -- Swagger

BankModel -- BankController
BankController -- BankView
BankView -- Swagger

VehicleModel -- VehicleController
VehicleController -- VehicleView
VehicleView -- Swagger

ContractModel -- ContractController
ContractController -- ContractView
ContractView -- Swagger

CreditContractModel -- CreditContractController
CreditContractController -- CreditContractView
CreditContractView -- Swagger

@enduml