@startuml

class User {
    -{static} String counter
    -int id
    -String name
    -String email
    -String password
    -boolean login(String password)
    -void changePassword(String oldPass, String newPass)
}
class Student {
    -Enrollment enrollment
    -boolean enroll(Registry registry)
    -boolean unenroll(Registry registry)
}
class Professor {
    -Registry[] registries
    -Subject[] getSubject()
    -Student[] getSubjectStudents(Subject subject)
}
class Secretary {
    -void allocateProfessor(Registry registry, Professor professor)
    -void createCourse(Registry registry, Professor professor)
}
class Enrollment {
    -int id
    -int semester
    -Student student
    -Course course
    -Registry[] registries
    -void addRegisty(Registry registry)
    -void deleteRegisty(Registry registry)
}
class Course {
    -int id
    -String name
    -int token
    -Semester[] semesters
    -void addSemester(Semester semester)
    -void deleteSemester(Semester semester)
}
class Semester {
    -int id
    -int period
    -Curriculum curriculum
    -Curriculum getCurriculum()
}
class Curriculum {
    -int id
    -String name
    -Registry[] registries
    -void addRegisty(Registry registry)
    -void deleteRegisty(Registry registry)
}
class Subject {
    -int id
    -String name
    -int hours
    -int token
}
class Registry {
    -int id
    -boolean required
    -Status status
    -Subject subject
    -Student[] student
    -Professor[] professors
    -Subject getSubject()
    -Status getStatus()
    -void addProfessor(Professor professor)
    -Professor deleteProfessor(Professor professor)
    -void addStudent(Student student)
    -Student deleteStudent(Student student)
    -void updateStatus(Status status)
}

enum Status {
    AVAILABLE
    CANCELED
    FULL
}

User <|-- Student
User <|-- Professor
User <|-- Secretary

Course "1" -- "1..*" Semester
Semester "1" -- "1" Curriculum
Curriculum "1" -- "1..*" Registry
Registry "0..*" -- "1" Subject
Student "0..*" -- "1..*" Course
(Student, Course) . Enrollment
Registry "0..*" -- "4..*" Student
Registry "0..*" -- "1..*" Professor

@enduml