@startuml

class User {
    -{static} String counter
    -int id
    -String name
    -String email
    -String password
    +boolean login(String password)
    +void changePassword(String oldPass, String newPass)
}
class Student {
    -Enrollment[] enrollment
    +void enroll(Registry registry)
    +void unenroll(Registry registry)
}
class Professor {
    -Registry[] registries
    +Subject[] getSubject()
    +Student[] getSubjectStudents(Subject subject)
}
class Secretary {
    +void allocateProfessor(Registry registry, Professor professor)
    +void dellocateProfessor(Registry registry, Professor professor)
    +void createCourse(Course course)
    +void deleteCourse(Course course)
    +void createSubject(Course course)
    +void deleteSubject(Course course)
    +void updateSubjectStatus(Subject subject, Status status)
    +void generateCurriculum(Semester semester)
}
class Enrollment {
    -{static} String counter
    -int id
    -int semester
    -Student student
    -Course course
    -Registry[] registries
    +void addRegisty(Registry registry)
    +void deleteRegisty(Registry registry)
}
class Course {
    -{static} String counter
    -int id
    -String name
    -int token
    -Semester[] semesters
    +void addSemester(Semester semester)
    +void removeSemester(Semester semester)
}
class Semester {
    -{static} String counter
    -int id
    -int period
    -Curriculum curriculum
    +Curriculum getCurriculum()
}
class Curriculum {
    -{static} String counter
    -int id
    -String name
    -Registry[] registries
    +void addRegisty(Registry registry)
    +void removeRegisty(Registry registry)
}
class Subject {
    -{static} String counter
    -int id
    -String name
    -int hours
    -int token
    -int getToken()
    -int getHours()
}
class Registry {
    -{static} String counter
    -int id
    -boolean required
    -Status status
    -Subject subject
    -Enrollment[] enrollment
    -Professor[] professors
    +Subject getSubject()
    +Status getStatus()
    +void addProfessor(Professor professor)
    +void removeProfessor(Professor professor)
    +void addEnrollment(Enrollment enrollment)
    +void removeEnrollment(Enrollment enrollment)
    +void updateStatus(Status status)
}

enum Status {
    AVAILABLE
    CANCELED
    FULL
}

User <|-- Student
User <|-- Professor
User <|-- Secretary

Course "1" -- "1..*" Semester
Semester "1" -- "1" Curriculum
Curriculum "1" -- "1..*" Registry
Registry "0..*" -- "1" Subject
Student "0..*" -- "1..*" Course
(Student, Course) . Enrollment
Registry "0..*" -- "4..*" Enrollment
Registry "0..*" -- "1..*" Professor

@enduml